### PR TITLE
Fix alternative index.html path

### LINKED ISSUE #36: `TypeError: Cannot read properties of undefined (reading 'source')`
Running `pnpm vite build` with the following config:
```ts
import { globSync } from "glob";
import { defineConfig } from "vite";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import path from "path";
import preact from "@preact/preset-vite";

const __dirname = dirname(fileURLToPath(import.meta.url));

export default defineConfig({
    plugins: [
        preact({
            prerender: {
                enabled: true
            }
        }),
    ],
    build: {
        rolldownOptions: {
            input: Object.fromEntries(
                globSync("src/**/index.html").map((file) => [
                    path.basename(path.dirname(file.slice(0, file.length - path.extname(file).length))),
                    resolve(__dirname, file),
                ]),
            ),
        },
    },
})
```
and project structure:
```
├── package.json
├── pnpm-lock.yaml
├── src
│   └── dashboard
│       ├── index.html
│       └── main.tsx
├── tsconfig.json
└── vite.config.ts
```

results in the following error:
```
vite v8.0.8 building client environment for production...
✓ 7 modules transformed.
✗ Build failed in 69ms
error during build:
Build failed with 1 error:

[plugin vite-prerender-plugin]
TypeError: Cannot read properties of undefined (reading 'source')
    at PluginContextImpl.generateBundle (file:///<snip>/front-end/node_modules/.pnpm/vite-prerender-plugin@0.5.13_vite@8.0.8/node_modules/vite-prerender-plugin/src/plugins/prerender-plugin.js:292:67)
    at PluginContextImpl.handler (file:///<snip>/front-end/node_modules/.pnpm/vite@8.0.8/node_modules/vite/dist/node/chunks/node.js:33214:13)
    at plugin (file:///<snip>/front-end/node_modules/.pnpm/rolldown@1.0.0-rc.15/node_modules/rolldown/dist/shared/bindingify-input-options-DYpBf1OG.mjs:1360:18)
    at plugin.<computed> (file:///<snip>/front-end/node_modules/.pnpm/rolldown@1.0.0-rc.15/node_modules/rolldown/dist/shared/bindingify-input-options-DYpBf1OG.mjs:1636:18)
    at aggregateBindingErrorsIntoJsError (file:///<snip>/front-end/node_modules/.pnpm/rolldown@1.0.0-rc.15/node_modules/rolldown/dist/shared/error-w0u7biK-.mjs:48:18)
    at unwrapBindingResult (file:///<snip>/front-end/node_modules/.pnpm/rolldown@1.0.0-rc.15/node_modules/rolldown/dist/shared/error-w0u7biK-.mjs:18:128)
    at #build (file:///<snip>/front-end/node_modules/.pnpm/rolldown@1.0.0-rc.15/node_modules/rolldown/dist/shared/rolldown-build-DtGk-m96.mjs:3313:34)
    at async buildEnvironment (file:///<snip>/front-end/node_modules/.pnpm/vite@8.0.8/node_modules/vite/dist/node/chunks/node.js:32954:64)
    at async Object.build (file:///<snip>/front-end/node_modules/.pnpm/vite@8.0.8/node_modules/vite/dist/node/chunks/node.js:33376:19)
    at async Object.buildApp (file:///<snip>/front-end/node_modules/.pnpm/vite@8.0.8/node_modules/vite/dist/node/chunks/node.js:33373:153)
    at async CAC.<anonymous> (file:///<snip>/front-end/node_modules/.pnpm/vite@8.0.8/node_modules/vite/dist/node/cli.js:778:3) {
  errors: [Getter/Setter]
```

Packages:
```
    "dependencies": {
        "preact": "10.29.1",
        "preact-render-to-string": "6.6.7"
    },
    "devDependencies": {
        "@preact/preset-vite": "^2.10.5",
        "glob": "^13.0.6",
        "vite": "8.0.8"
    }
```

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes https://github.com/preactjs/vite-prerender-plugin/issues/36

When the `html` entry file is at a different position the path will be different, this fixes that case by looking through the assets to find it.

### CODE REVIEW

File: src/plugins/prerender-plugin.js [hunk 1]
```diff
@@ -106,6 +104,17 @@ export function prerenderPlugin({ prerenderScript, renderTarget, additionalPrere
...
+    };
+
+    /**
+     * From the non-external scripts in entry HTML document, find the one (if any)
+     * that provides a `prerender` export
+     *
+     * @param {import('vite').Rollup.InputOption} input
+     */
+    const getPrerenderScriptFromHTML = async (input) => {
+        const entryHtml = getPrerenderEntryHtml(input);
```
Comment (rschristian) [inline src/plugins/prerender-plugin.js]: We don't need this call, `getPrerenderScriptFromHTML` is only ever called after `getPrerenderEntryHtml`, which sets `prerenderEntryHtml` plugin-wide. Can  just read from it instead

File: src/plugins/prerender-plugin.js [hunk 2]
```diff
@@ -90,12 +91,9 @@ export function prerenderPlugin({ prerenderScript, renderTarget, additionalPrere
     const tmpDirId = 'headless-prerender';
 
     /**
-     * From the non-external scripts in entry HTML document, find the one (if any)
-     * that provides a `prerender` export
-     *
      * @param {import('vite').Rollup.InputOption} input
      */
-    const getPrerenderScriptFromHTML = async (input) => {
+    const getPrerenderEntryHtml = (input) => {
```
Comment (rschristian) [inline src/plugins/prerender-plugin.js:96]: Nit, but existing function is `...HTML` & the new fn & var are `...Html`. Consistency either way (changing the existing name or new names, I have no preference) would be appreciated.

File: src/plugins/prerender-plugin.js [hunk 3]
```diff
@@ -288,9 +300,25 @@ export function prerenderPlugin({ prerenderScript, renderTarget, additionalPrere
...
+                            output.fileName.endsWith('.html') &&
+                            (output.originalFileName === prerenderEntryHtml ||
+                                output.originalFileNames?.includes(prerenderEntryHtml)),
+                    )) ||
+                bundle['index.html'] ||
+                Object.values(bundle).find(
+                    (output) => output.type === 'asset' && output.fileName.endsWith('.html'),
+                );
+
+            if (!entryHtmlAsset || entryHtmlAsset.type !== 'asset') {
```
Comment (rschristian) [inline src/plugins/prerender-plugin.js]: Type guard looks to be redundant, I don't know how in the world a user would ever create a `.html` _chunk_.

```suggestion
            if (!entryHtmlAsset) {
```

**Review by rschristian — APPROVED** [review]
Cheers, appreciate it

File: src/plugins/prerender-plugin.js [hunk 4]
```diff
@@ -319,10 +346,7 @@ export function prerenderPlugin({ prerenderScript, renderTarget, additionalPrere
 
                 const assetPath = path.join(tmpDir, output);
                 await fs.mkdir(path.dirname(assetPath), { recursive: true });
-                await fs.writeFile(
-                    assetPath,
-                    /** @type {OutputChunk} */ (bundle[output]).code,
-                );
+                await fs.writeFile(assetPath, /** @type {OutputChunk} */ (bundle[output]).code);
```
Comment (rschristian) [inline src/plugins/prerender-plugin.js]:
```suggestion
                await fs.writeFile(
                    assetPath,
                    /** @type {OutputChunk} */ (bundle[output]).code,
                );
```

File: src/plugins/prerender-plugin.js [hunk 5]
```diff
@@ -348,9 +372,7 @@ export function prerenderPlugin({ prerenderScript, renderTarget, additionalPrere
                         // do something in browsers only
                     }`.replace(/^ {20}/gm, '');
 
-                const stack = StackTraceParse(e).find((s) =>
-                    s.getFileName()?.includes(tmpDirId),
-                );
+                const stack = StackTraceParse(e).find((s) => s.getFileName()?.includes(tmpDirId));
```
Comment (rschristian) [inline src/plugins/prerender-plugin.js]:
```suggestion
                const stack = StackTraceParse(e).find((s) =>
                    s.getFileName()?.includes(tmpDirId),
                );
```

File: src/plugins/prerender-plugin.js [hunk 6]
```diff
@@ -390,9 +412,7 @@ export function prerenderPlugin({ prerenderScript, renderTarget, additionalPrere
 
             let prerender;
             try {
-                const m = await import(
-                    `file://${path.join(tmpDir, prerenderEntry.fileName)}`
-                );
+                const m = await import(`file://${path.join(tmpDir, prerenderEntry.fileName)}`);
```
Comment (rschristian) [inline src/plugins/prerender-plugin.js]:
```suggestion
                const m = await import(
                    `file://${path.join(tmpDir, prerenderEntry.fileName)}`
                );
```
